from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables from .env file
env_path = Path(__file__).parent / ".env"
if env_path.exists():
    load_dotenv(env_path)


@dataclass
class SqlQuery:
    sql: str
    description: str


SYSTEM_PROMPT = """Write ONLY a SQL SELECT query for SQLite. No INSERT/UPDATE/DELETE/DROP. Return SQL only, no formatting."""


def _configure_gemini() -> None:
    """Configure the Gemini API client with the API key."""
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY environment variable is not set. "
            "Set it to your Google Gemini API key to enable NL→SQL. "
            "Get your key from: https://makersuite.google.com/app/apikey"
        )
    genai.configure(api_key=api_key)


def _sanitize_sql(sql: str) -> str:
    """Allow only a single SELECT statement without dangerous keywords."""
    cleaned = sql.strip().strip(";").strip()
    lowered = cleaned.lower()

    # First check for dangerous keywords (even if they appear in a SELECT statement)
    banned_keywords = [
        "insert ",
        "update ",
        "delete ",
        "drop ",
        "alter ",
        "create ",
        "attach ",
        "detach ",
        "pragma ",
        "vacuum",
    ]
    for kw in banned_keywords:
        if kw in lowered:
            raise ValueError(f"Dangerous keyword detected in SQL: {kw.strip()!r}")

    # Then check that it starts with SELECT
    if not lowered.startswith("select"):
        raise ValueError("Only SELECT statements are allowed.")

    # Disallow multiple statements separated by semicolons.
    if ";" in cleaned:
        raise ValueError("Multiple SQL statements are not allowed.")

    return cleaned


def question_to_sql(
    question: str,
    schema_description: str,
    model_name: Optional[str] = None,
) -> SqlQuery:
    """
    Use Google Gemini to translate a natural language question
    into a safe SQL SELECT query for the given SQLite schema.
    """
    _configure_gemini()
    # Use gemini-2.5-flash (valid model)
    if model_name is None:
        model_name = os.getenv("GEMINI_CHAT_MODEL", "gemini-2.5-flash")
    model = genai.GenerativeModel(model_name)

    # Shorter, more direct prompt for faster responses
    prompt = f"{SYSTEM_PROMPT}\n\nSchema:\n{schema_description}\n\nQuestion: {question}\n\nSQL:"

    try:
        # Use faster generation config
        response = model.generate_content(
            prompt,
            generation_config={
                "temperature": 0,
                "max_output_tokens": 500,  # Limit output for speed
            },
        )
        content: Optional[str] = response.text if response.text else None
    except Exception as e:
        raise RuntimeError(f"Failed to generate SQL with Gemini: {e}")

    if not content:
        raise RuntimeError("No content returned from Gemini when generating SQL.")

    # Content should already be plain SQL, but be defensive in case formatting slips in.
    # Try to extract from ```sql ... ``` if present.
    match = re.search(r"```sql(.*)```", content, re.IGNORECASE | re.DOTALL)
    if match:
        raw_sql = match.group(1)
    else:
        raw_sql = content

    sql = _sanitize_sql(raw_sql)
    description = "SQL generated by Google Gemini based on your question and the detected schema."
    return SqlQuery(sql=sql, description=description)

